name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ github.base_env.DOTNET_VERSION }}

      - name: Echo version
        run: echo ${{ github.base_env.DOTNET_VERSION }}

      - name: Publish
        run: dotnet publish --configuration Release --output ./out
